/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package garbagedetection;

import java.io.File;
import java.util.Vector;

/**
 *
 * @author Syed Musthafa
 */
public class Classification extends javax.swing.JFrame {

    static String snappath = "snapshots";
    static long len;
    public Classification() {
        initComponents();
        getSnapshotImages();
    }

    Classification(String videofile) {
        initComponents();
        try {
            double d = 0.5;
            VideoToSnapshot.SECONDS_BETWEEN_FRAMES = d;
            new VideoToSnapshot().SanpshotConversion(videofile, "0.5");
            boolean choice = check(rootPaneCheckingEnabled);
            if (choice) {
                getSnapshotImages();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public void getSnapshotImages() {
       try {
            Vector c = new Vector();
            Vector r = new Vector();

            c.add("Video Images");
            c.add("Video Images");
            File tf = new File("");
            File t = new File(tf.getCanonicalPath() + "\\snapshots");
            String[] flist = t.list();
            for (int i = 0; i < flist.length; i++) {
                Vector r1 = new Vector();
                r1.add("<html><img src='file:///" + t.getAbsolutePath().replace("\\", "/") + "/" + i + ".jpg' width='150' height='150' /></html>");
                r1.add("<html><img src='file:///" + t.getAbsolutePath().replace("\\", "/") + "/" + (i + 1) + ".jpg' width='150' height='150' /></html>");
                r.add(r1);
            }


            jTable1.setModel(new javax.swing.table.DefaultTableModel(r, c));
            jTable1.setRowHeight(120);
         //   jTable1.setColumnSelectionInterval(30, 30);
        } catch (Exception e) {

            e.printStackTrace();
        }
    }

    public boolean check(boolean ch) {
        return ch;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datasetpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datasetpanel.setBackground(new java.awt.Color(255, 255, 255));
        datasetpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Video Shots", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        datasetpanel.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        datasetpanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 550, 380);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Classification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datasetpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(datasetpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
        File tf = new File("");
        new DatasetConversion(tf.getCanonicalPath() + "\\snapshots").setVisible(true);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Classification().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datasetpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
