/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aathisithan
 */
import javax.swing.JOptionPane;
import java.util.*;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;
public class VotingFrame extends javax.swing.JFrame {

        private static BigInteger p,q;
	private static BigInteger n;
	private static BigInteger temp;
	private static BigInteger m;
	private static BigInteger g,value1,value2;
	private static BigInteger c,r;
        private static String vote;
        private static int i=0;
    
    public VotingFrame() {
        initComponents();
        setDefaultCloseOperation(VotingFrame.DISPOSE_ON_CLOSE);
    }
    public VotingFrame(String id,String Name){
        initComponents();
        this.setResizable(false);
        voteridlabel.setText(id);
        voternamelabel.setText(Name);
        setDefaultCloseOperation(UserLoginFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radiobutton1 = new javax.swing.JRadioButton();
        radiobutton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radiobutton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voternamelabel = new javax.swing.JLabel();
        voteridlabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        buttonGroup1.add(radiobutton1);
        radiobutton1.setText("1");
        radiobutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobutton2);
        radiobutton2.setText("2");
        radiobutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton2ActionPerformed(evt);
            }
        });
        radiobutton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radiobutton2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radiobutton2KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       e-voting system");

        buttonGroup1.add(radiobutton3);
        radiobutton3.setText("3");
        radiobutton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobutton3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radiobutton3MouseReleased(evt);
            }
        });
        radiobutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton3ActionPerformed(evt);
            }
        });
        radiobutton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radiobutton3KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Candidate A");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Candidate B");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Candidate C");

        voternamelabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        voternamelabel.setForeground(new java.awt.Color(255, 255, 255));
        voternamelabel.setText("jLabel5");
        voternamelabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                voternamelabelInputMethodTextChanged(evt);
            }
        });

        voteridlabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        voteridlabel.setForeground(new java.awt.Color(255, 255, 255));
        voteridlabel.setText("jLabel5");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("4");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("5");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Candidate D");

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Candidate E");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(voternamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(voteridlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radiobutton2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(radiobutton1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(radiobutton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(263, 263, 263))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voternamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voteridlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobutton1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobutton2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobutton3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void radiobutton1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        if(buttonGroup1.getSelection()!=null){
            int response=JOptionPane.showConfirmDialog(this,"Submit your vote?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        radiobutton1.setActionCommand("1");
        radiobutton2.setActionCommand("2");
        radiobutton3.setActionCommand("3");       
        jRadioButton1.setActionCommand("4");       
        jRadioButton2.setActionCommand("5");       
        //JOptionPane.showMessageDialog(null,buttonGroup1.getSelection().getActionCommand()+buttonGroup1.getSelection().getActionCommand());
        vote=buttonGroup1.getSelection().getActionCommand();
        encryption(vote);
        String Name= voternamelabel.getText();
        String Id=voteridlabel.getText();
        String v=c.toString();
        switch(vote){
            case "1": v=v+"1";
                    break;
            case "2": v=v+"2";
                    break;
            case "3": v=v+"3";
                    break;
            case "4":v=v+4;
                   break;
            default:v=v+5;
                  break;
        }
        try{
                  Class.forName("com.mysql.cj.jdbc.Driver");  
                  Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingdbb","root","");
                  String query = "INSERT INTO `votelist`(`Votername`, `VoterID`,`Vote`) VALUES (?,?,?)";                                                                             
                  PreparedStatement ps=con.prepareStatement(query);
                  ps.setString(1, Name);
                  ps.setString(2, Id);
                  ps.setString(3, v);
                  ps.executeUpdate();
                  
        }
        catch(Exception e){
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(null,"Your Vote added Succesfully");
        dispose();
        }
        else{
            buttonGroup1.clearSelection();
        }
       }
       else{
           JOptionPane.showMessageDialog(null,"Please Select Your Vote");
       }
        
    }                                        
    public void encryption(String v){
        if(i==0){
            publickey();
        }
        i++;
         m=BigInteger.valueOf(Long.parseLong(v));
        System.out.println(v);
	value1=compute(g,m);
	value2=compute(r,n);
	c=(value1.multiply(value2)).mod(n.multiply(n));
	System.out.println(c);
           
    }
    public void publickey(){
     Random rand = new Random(); 
     r=new BigInteger(5,rand);
    p= new BigInteger(5,rand);

    q= new BigInteger(5,rand);
 
   p=prime(p);  
   q=prime(q);
   n=p.multiply(q);
   temp=(p.subtract(BigInteger.valueOf(1))).multiply(q.subtract(BigInteger.valueOf(1)));
     if(gcd(n,temp).compareTo(BigInteger.valueOf(1))==0){
        System.out.println(p+" "+q+" "+n+" "+temp);
       }
       else{
        	 System.out.println("You need to get different prime numbers");
	         publickey();
          }
         g=new BigInteger(5,rand);
         if(g.compareTo(BigInteger.valueOf(0))>0){
		 System.out.println("publickeys:");
		 System.out.println("n:"+n+" g:"+g);
         }
         else{
               g=new BigInteger(5,rand);
               System.out.println("publickeys:");
	       System.out.println("n:"+n+" g:"+g);
         }
        }
    public static BigInteger prime(BigInteger num){
	Random rand = new Random(); 
	if(num.isProbablePrime(1))
		return num;
	return prime(num= new BigInteger(5,rand));
}
    public static BigInteger gcd(BigInteger num1,BigInteger num2){
	if(num2.compareTo(BigInteger.valueOf(0))==0)
		return num1;
	return gcd(num2,num1.remainder(num2));
	
}
 public static BigInteger compute(BigInteger num1,BigInteger num2){
	Integer number=num2.intValue();
	return (num1.pow(number));
}
    private void voternamelabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                      
 
    }                                                     

    private void radiobutton2KeyPressed(java.awt.event.KeyEvent evt) {                                        
        
    }                                       

    private void radiobutton2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
    }                                            

    private void radiobutton2KeyReleased(java.awt.event.KeyEvent evt) {                                         
       
    }                                        

    private void radiobutton3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
         
       
    }                                            

    private void radiobutton3KeyReleased(java.awt.event.KeyEvent evt) {                                         
         
    }                                        

    private void radiobutton3MouseClicked(java.awt.event.MouseEvent evt) {                                          
        
    }                                         

    private void radiobutton3MouseReleased(java.awt.event.MouseEvent evt) {                                           
        
    }                                          

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton radiobutton1;
    private javax.swing.JRadioButton radiobutton2;
    private javax.swing.JRadioButton radiobutton3;
    private javax.swing.JLabel voteridlabel;
    private javax.swing.JLabel voternamelabel;
    // End of variables declaration                   
}
