/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otp;

import atm.AtmLogin;
import atm.IPINENTER1;
import atm.PinGen;
import otp.OtpEnter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

public class OtpLogin extends javax.swing.JFrame {
     Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    Connection con1=null;
    Statement st1=null;
    ResultSet rs1=null;
     Statement st2=null;
    ResultSet rs2=null;
    
    String pwd;
    String acc;
    String count;
    String mailId;
    String name;
    
   
    String email;
     private String tmp;
    private String otp1 = "";
        private String location = "";

    private String loc="";
      private String mail;
      
    

    /**
     * Creates new form OtpLogin
     */
    public OtpLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Secure OTP Generation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter your Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Account Number");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Password");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continue-button.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton1)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
     acc= jTextField1.getText().trim();
      pwd=jPasswordField1.getText().toString();
      DB.database.getConnection();
      if (acc.isEmpty() || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Account Number and Password", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else if (DB.database.checkLogin(acc, pwd)) {
//a pop-up box
            
              String c="Exit";
             try {    
	                	
	          Class.forName("com.mysql.jdbc.Driver");
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/prj","root","root");
	           st1 = con1.createStatement();
	             rs1 = st1.executeQuery("select status from tbl_registration where account='"+acc+"'");
                     if(rs1.next())
                     {
                         count=rs1.getString("status");
                     }
                     st2 = con1.createStatement();
	             rs2 = st1.executeQuery("select name from tbl_registration where account='"+acc+"'");
                     if(rs2.next())
                     {
                        name=rs2.getString("name");
                     }
                    st2 = con1.createStatement();
	             rs2 = st1.executeQuery("select email from tbl_registration where account='"+acc+"'");
                     if(rs2.next())
                     {
                        mailId=rs2.getString("email");
                     }
                    
           }catch(Exception e){
               
               System.out.println(e);
                        
                    }  
          
          if(count.equals(c))
          {
              
             JOptionPane.showMessageDialog(null, "You have logged in successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
              DB.database.setname(name); 
             DB.database.setmail(mailId);
          this.setVisible(false);  
          new OtpCont().setVisible(true);
              
          }
            
          else{
              
              try {    
	                	
	          Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3308/prj","root","root");
	           st = con.createStatement();
	             int i = st.executeUpdate("update tbl_registration set status='"+c+"' where account='"+acc+"'");
                     st2 = con1.createStatement();
	             rs2 = st1.executeQuery("select name from tbl_registration where account='"+acc+"'");
                     if(rs2.next())
                     {
                        name=rs2.getString("name");
                     }
                    
                    st2 = con1.createStatement();
	             rs2 = st1.executeQuery("select email from tbl_registration where account='"+acc+"'");
                     if(rs2.next())
                     {
                        mailId=rs2.getString("email");
                     }
           }catch(Exception e){
               
               System.out.println(e);
                        
                    }  
         
            JOptionPane.showMessageDialog(null, "You have logged in successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
           DB.database.setname(name); 
            DB.database.setmail(mailId);
            this.setVisible(false);
          new OtpCont().setVisible(true);
          }
           
          
        
        } else {
            JOptionPane.showMessageDialog(null, "Invalid User Name Or Account Name", "Login Error", JOptionPane.ERROR_MESSAGE);
        }  
    
      jTextField1.setText("");
      jPasswordField1.setText("");

                 
            
           String[] solutionArray = {"R", "G", "B", "Y", "P", "W", "V","O","A","S","L","M"};
           
        String[] locationArray={"L","M","R"};
        
        DB.database.shuffleArray(solutionArray);
        DB.database.locationArray(locationArray);

        for (int i = 0; i < 4; i++) {

            tmp = solutionArray[i];

            otp1 = otp1 + tmp;
        }
        
        for (int i = 0; i < 1; i++) {

            tmp = locationArray[i];

            loc = loc + tmp;
        }

            
 try {    
	                	
	          Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3308/prj","root","root");
	           st = con.createStatement();
	            String sql=" Update tbl_registration set otp='"+otp1+"',otpl='"+loc+"' where account='"+acc+"'" ;
                     
               st.executeUpdate(sql);
	            
	           
                    
           }catch(Exception e){
               
               System.out.println(e);
                        
                    }  
          finally{
            try {
                st.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(OtpEnter.class.getName()).log(Level.SEVERE, null, ex);
            }
              
          }

   
   
         DB.database.setmail(mailId); 
           
           
      
      
      jTextField1.setText("");
      jPasswordField1.setText("");
              

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtpLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
